[project]
name = "orbit"
version = "0.1.0"
description = "Orbit is a tool for managing your daily tasks"
requires-python = ">=3.13"
dependencies = [
    "flask==3.1.2",
    "flask-wtf==1.2.2",
    "python-dotenv==1.1.1",
]
